### ISSUE TITLE
Alignment problem with labels and rotate x axis

### ISSUE THREAD

**Issue by sibliss** [naver/billboard.js#25] opened 2017-06-20 16:40 UTC
## Description
I have a bar graph (the same as the example provided here: https://cdn.rawgit.com/naver/billboard.js/8413325d/demo/#Axis.RotatedAxis,
 but with just the bar type of data. The only difference is that the data provided are in json format with a text value:
`[
      {text: "text1", value: 5},
      {text: "text2", value: 10},
      {text: "text3", value: 15},
]`

I would like to have the `text` value of every object as text label of the corresponding value. So I added this code to the graph:

`axis: {
       x: {
           type: "category",
           categories: labels,
      },
 rotated: true,
},`

but the label are not aligned with the values. In that specific case I can see the three bars with the value of 5, 10 and 15 but the labels on the y axis (the x rotated) are just two.

<img width="295" alt="screen shot 2017-06-20 at 6 34 15 pm" src="https://user-images.githubusercontent.com/28410128/27344584-1cef8e9e-55e7-11e7-8164-042210c3efaf.png">

In that case I should see a third "test1" aligned with the bar in the middle. On top of that you can notice that the label that are present are not aligned correctly with the respective bars.

## Steps to check or reproduce

This is the code that  cause the problem:

```js
            const data = this.data.map(i => i.value);
            const labels = this.data.map(i => i.text);
            data.unshift("data1");
            billboard.bb.generate({
                data: {
                    columns: [
                        data,
                    ],
                    types: {
                        data1: "bar",
                    },
                },
                axis: {
                    x: {
                        type: "category",
                        categories: labels,
                    },
                    rotated: true,
                },
                bindto: `.${this.graphUniqueClass}`,
```

**Comment by netil** [comment] 2017-06-21 07:21
@sibliss confirmed the issue. It seems like issuing on initializing, because after generation, do resize of the window or implicitly calling `.resize()` will be positioned well.

The generation code is like:
```js
bb.generate({
	"data": {
		"columns": [
			["data1", 5, 10, 15]
		],
		"type": "bar"
	},
	"axis": {
		x: {
			type: "category",
			categories: ["text1", "text2", "text3"],
		},
		"rotated": true
	},
});
```
and the correct rendering should be :
![image](https://user-images.githubusercontent.com/2178435/27371900-87d3d600-569d-11e7-8345-b1041d2e8f57.png)

For this moment, do 
```js
const chart = bb.generate(...);
chart.resize();
```

**Comment by laurencedorman** [comment] 2017-07-19 16:38
I see this issue is closed, does this mean that you regard it as fixed or is there another issue for it now? I am asking because I am using the most recent version of billboard and I have come across this problem

**Comment by netil** [comment] 2017-07-20 07:23
@laurencedorman, I'll try to check again

**Comment by netil** [comment] 2017-08-11 04:57
@laurencedorman, it's still happening?
with the latest, seems problem has been solved.
- https://jsbin.com/lovisoy/edit?html,js,output
![image](https://user-images.githubusercontent.com/2178435/29201800-99aee73a-7e9c-11e7-83c9-196a6d9bf74a.png)

If you have any other issue rather than that or reproduction code, let me know for check.
For now, closing the issue.

**Comment by rtmalone** [comment] 2018-02-08 18:11
I just confirmed this issue has reappeared in v1.2.0. I installed v1.0.1 and the issue corrected itself to center on the bar.

**Comment by fcodias** [comment] 2018-12-03 14:36
Hi @netil, I think the problem is related with the legend attribute. This still happening when the legend attribute is false.

https://jsbin.com/cabemapudu/1/edit?html,js,output

**Comment by netil** [comment] 2018-12-04 06:46
@fcodias got it thanks.
It seems to have miscalculation with the legend occupied area.

**Closed** 2018-12-04 09:18 UTC
Labels: bug
