### ISSUE TITLE
data.selection.multiple: false causes error

### ISSUE THREAD

**Issue by Hanterdro** [naver/billboard.js#112] opened 2017-08-16 09:01 UTC
Setting `data.selection.multiple` to `false` causes 

```
d3.min.js:2 Uncaught TypeError: t.getAttribute is not a function
    at W (d3.min.js:2)
    at V (d3.min.js:2)
    at pt.classed (d3.min.js:2)
    at SVGPathElement.<anonymous> (selection.js:172)
    at pt.each (d3.min.js:2)
    at ChartInternal.toggleShape (selection.js:163)
    at SVGCircleElement.<anonymous> (interaction.js:397)
    at pt.each (d3.min.js:2)
    at SVGRectElement.<anonymous> (interaction.js:397)
    at SVGRectElement.<anonymous> (d3.min.js:2)
```

when clicking on a datapoint.

"billboard.js": "1.0.1",
"d3": "4.10.0",

```
    let chart = bb.generate({
        "data": {

            selection: {
                enabled: true,
                multiple: false
            },
            "columns": [
                [
                    "data1",
                    30,
                    200,
                    100,
                    400,
                    150,
                    250
                ],
                [
                    "data2",
                    50,
                    20,
                    10,
                    40,
                    15,
                    25
                ],
                [
                    "data3",
                    4,
                    5,
                    10,
                    15,
                    17,
                    20
                ]
            ],
            "axes": {
                "data1": "y",
                "data2": "y"
            }
        },

        "axis": {
            "x": {
                tick: {
                    format: data => `${data}°`,
                    outer: false
                }
            },
            y: {
              tick: {
                  outer: false
              }
            }

        },
        "bindto": "#LineChart"
    });
```

**Comment by netil** [comment] 2017-08-16 09:35
thanks @Hanterdro for reporting. It's caused by the wrong scoping.
This will be fixed ASAP.

**Closed** 2017-08-17 05:10 UTC
Labels: bug
