### ISSUE TITLE
Wrong Tooltip position with Padding property.

### ISSUE THREAD

**Issue by cylnclk** [naver/billboard.js#1155] opened 2019-12-06 14:45 UTC
## Description
When we give the donut's wrapper the padding  property, we detected that the mouseover function does not work correctly, the tooltip element get the position wrong .

## Steps to check or reproduce
1. Go [example](https://naver.github.io/billboard.js/demo/#)
2. Give the "div" padding property to "index.html" page.
i.e;
   `<div id='donutChart' style="padding:25px"></div>`
3.We can see the wrong result for mouseover when we move the mouse over a chart's field.

Sorry for my bad English.

## Screenshot
![issue](https://user-images.githubusercontent.com/9307855/70331180-ffb8b700-184f-11ea-830d-da939516c9e5.png)

**Comment by netil** [comment] 2019-12-13 07:22
Hi @cylnclk, thanks for the report.
It seems firing event multiple times behaving differently without padding.

I'll be heading this issue.

**Comment by netil** [comment] 2019-12-19 08:54
Is a side-effect caused by #1124, removing `pointer-events: none` css prop from the tooltip element.
The usability on making tooltip element to receive event isn't worth than the basic behavior of the chart usage, so it need to be revert the changes.

**Comment by netil** [comment] 2019-12-19 09:06
@cylnclk, just for workaround for `1.11.0` release, add below css to your project.
The change will be released as patch soon.

```css
.bb-tooltip-container {
	pointer-events: none;
}
```

**Closed** 2019-12-19 09:26 UTC
Labels: bug
